iAndhra/app/models/lulc.py
from iAndhra.app.db import db

class LULC(db.Model):
    __tablename__ = 'lulc'
    
    id = db.Column(db.Integer, primary_key=True)
    lulc_name = db.Column(db.String(100), unique=True, nullable=False)
    census_description = db.Column(db.String(100), nullable=False)
    display_name = db.Column(db.String(100), nullable=False)
    catchment = db.Column(db.String(40))
    
    def __init__(self, lulc_name, census_description, display_name, catchment):
        """
        Initialize the LULCMaster instance with the provided lulc_name.
        """
        self.lulc_name = lulc_name
        self.census_description = census_description
        self.display_name = display_name
        self.catchment = catchment
    
    def __repr__(self):
        """
        Provides a string representation of the LULCMaster instance.
        """
        return f"<LULC(id={self.id}, lulc_name='{self.lulc_name}', census_description = '{self.census_description}', display_name = '{self.display_name}', catchment: '{self.catchment})>"
    
    def json(self):
        """
        Returns a JSON serializable dictionary representation of the LULCMaster instance.
        """
        return {
            "id": self.id,
            "lulc_name": self.lulc_name,
            "census_description": self.census_description,
            "display_name": self.display_name,
            "catchment":self.catchment
        }
        
    @classmethod
    def get_all_lulc(cls):
        query = db.session.query(cls.id,cls.display_name).all()
        if query:
            json_data = [{'lulc_id':item.id,'lulc_name':item.display_name} for item in query]
            return json_data

iAndhra/app/models/rainfall.py
# from datetime import datetime
from sqlalchemy import Numeric, alias, and_, cast, func
from iAndhra.app.db import db
from iAndhra.app.models.block_rainfall import BlockRainfall
from iAndhra.app.models.block_territory import BlockTerritory
from iAndhra.app.models.blocks import Block

class Rainfall(db.Model):
    __tablename__ = 'rainfall_data'

    id = db.Column(db.Integer, primary_key=True)
    month_year = db.Column(db.DateTime,nullable=False)
    normal = db.Column(db.Float(53), nullable=False)
    actual = db.Column(db.Float(53), nullable=False)
    district_id = db.Column(db.ForeignKey('districts.id'), nullable=False)
    
    district = db.relationship('District', backref=db.backref("rainfall_data", lazy="dynamic"))

    def __init__(self, month_year, normal, actual, district_id):
        self.month_year = month_year
        self.normal = normal
        self.actual = actual
        self.district_id = district_id

    def json(self):
        return {
            'id': self.id,
            'month_year': self.month_year,
            'normal': self.normal,
            'actual': self.actual,
            'district_id': self.district_id 
        }
    
    @classmethod
    def get_census_data_rainfall(cls, district_id):
        results = db.session.query(
                        cls.actual,
                        cls.normal,
                        func.to_char(cls.month_year, 'Mon-YY').label("month"),
                        cls.month_year
                    ).filter(cls.district_id == district_id
                    ).order_by(cls.month_year
                    ).all()
                
        if results:
            result = [{'month':result[2],'actual':result[0],'normal':result[1],'date':result[3]} for result in results]
        else: 
            result = [{'month':0,'actual':0,'normal':0}]
        return result
 
    @classmethod
    def get_monthwise_rainfall(cls, block_id, district_id):
        block_rainfall_subquery = db.session.query(
                func.to_char(BlockRainfall.month_year, 'FMMon-YY').label('date'),
                func.round(func.sum(BlockRainfall.actual).cast(Numeric), 2).label('actual'),
                func.round(func.sum(BlockRainfall.normal).cast(Numeric), 2).label('normal'),
            ).join(BlockTerritory, BlockTerritory.id == BlockRainfall.bt_id
            ).join(Block, Block.id == BlockTerritory.block_id
            ).filter(Block.id == block_id
            ).group_by(func.to_char(BlockRainfall.month_year, 'FMMon-YY')
            ).subquery()

        # Subquery for rainfall_data
        rainfall_data_subquery = db.session.query(
                func.to_char(Rainfall.observation_date, 'FMMon-YY').label('date'),
                func.round(func.sum(Rainfall.actual).cast(Numeric), 2).label('actual'),
                func.round(func.sum(Rainfall.normal).cast(Numeric), 2).label('normal'),            
            ).filter(Rainfall.district_id == district_id
            ).group_by(func.to_char(Rainfall.observation_date, 'FMMon-YY')
            ).subquery()

        # Main query
        query = db.session.query(
                func.to_char(Rainfall.observation_date, 'FMMon-YY').label('month_year'),
                func.coalesce(block_rainfall_subquery.c.actual, rainfall_data_subquery.c.actual, 0).label('actual'),
                func.coalesce(block_rainfall_subquery.c.normal, rainfall_data_subquery.c.normal, 0).label('normal'),
            ).outerjoin(
                block_rainfall_subquery,
                func.to_char(Rainfall.observation_date, 'FMMon-YY') == block_rainfall_subquery.c.date,
            ).outerjoin(
                rainfall_data_subquery,
                func.to_char(Rainfall.observation_date, 'FMMon-YY') == rainfall_data_subquery.c.date,
            ).group_by(
                func.to_char(Rainfall.observation_date, 'FMMon-YY'),
                block_rainfall_subquery.c.actual,
                block_rainfall_subquery.c.normal,
                rainfall_data_subquery.c.actual,
                rainfall_data_subquery.c.normal,
            ).order_by(func.min(Rainfall.observation_date))

        results = query.all()
        if results:
            result = [{'month':result[0],'actual':result[1],'normal':result[2]} for result in results]
        else: 
            result = [{'month':0,'actual':0,'normal':0}]
        return result
        # '''
        # SELECT
        # TO_CHAR(observation_date, 'Mon-YYYY') AS observation,
        # SUM(actual) AS actual
        # FROM
        #     rainfall_data
        # WHERE
        #     EXTRACT(YEAR FROM observation_date) = 2023 and district_id = 639
        # GROUP BY
        #     observation, EXTRACT(MONTH FROM observation_date), EXTRACT(YEAR FROM observation_date)
        # ORDER BY
        #     EXTRACT(YEAR FROM observation_date), EXTRACT(MONTH FROM observation_date);
        # '''
       

iAndhra/app/routes/desktop.py
from flask import Blueprint, flash, get_flashed_messages, json, jsonify, redirect, render_template, request, session, url_for
from flask_login import current_user, login_required

from iAndhra.app.classes.block_data import BlockData
from iAndhra.app.classes.budget_data import BudgetData
from iAndhra.app.classes.helper import HelperClass
from iAndhra.app.models import BlockTerritory
from iAndhra.app.models.block_pop import BlockPop


blp = Blueprint('desktop','desktop')

@blp.route('/status')
def status():
    session_data = session.get('payload')
    if not session_data:
        return redirect(url_for('mobile.index'))
    else:
        payload = json.loads(session_data)
    progress_status = BlockData.get_progress_status(village_id=payload['village_id'],
                                            panchayat_id=payload['panchayat_id'],
                                            block_id=payload['block_id'], 
                                            district_id=payload['district_id'])
    message = get_message()
    return render_template('desktop/home.html',
                           progress = progress_status,
                           flash_message = get_message(),
                           breadcrumbs=HelperClass.get_breadcrumbs(payload),
                           menu= HelperClass.get_main_menu())


@blp.route('/human', methods=['POST','GET'])
@login_required
def human():
    if request.method=='POST':
        json_data = request.json
        BlockData.update_human(json_data, current_user.id)
        flash('Population Data is Validated/Updated')
        return jsonify({'redirect_url': url_for('.status')})
    session_data = session.get('payload')
    if not session_data:
        return redirect(url_for('mobile.index'))
    else:
        payload = json.loads(session_data)
    human = BlockData.get_human_consumption(village_id=payload['village_id'],
                                            panchayat_id=payload['panchayat_id'],
                                            block_id=payload['block_id'], 
                                            district_id=payload['district_id'],
                                            user_id=current_user.id)
    if human:
        
        is_approved = (
            all(row['is_approved'] for row in human if row['is_approved'] is not None) 
            and any(row['is_approved'] is not None for row in human)
        )
    else:
        is_approved = False
        human = BlockData.get_dummy_crops(village_id=payload['village_id'],
                                            panchayat_id=payload['panchayat_id'],
                                            block_id=payload['block_id'], 
                                            district_id=payload['district_id'])
        
    return render_template('desktop/demand/human.html', 
                           human=human, 
                           human_data=json.dumps(human), 
                           is_approved=is_approved,
                           breadcrumbs=HelperClass.get_breadcrumbs(payload),
                           menu= HelperClass.get_demand_menu())

@blp.route('/livestocks', methods=['POST','GET'])
@login_required
def livestocks():
    if request.method=='POST':
        json_data = request.json
        BlockData.update_livestock(json_data, current_user.id)
        flash('Livestock Data is Validated/Updated')
        return jsonify({'redirect_url': url_for('.status')})
    session_data = session.get('payload')
    if not session_data:
        return redirect(url_for('mobile.index'))
    else:
        payload = json.loads(session_data)
    livestocks = BlockData.get_livestock_consumption(village_id=payload['village_id'],
                                            panchayat_id=payload['panchayat_id'],
                                            block_id=payload['block_id'], 
                                            district_id=payload['district_id'],
                                            user_id=current_user.id)
    if livestocks:
        is_approved = (
            all(row['is_approved'] for row in livestocks if row['is_approved'] is not None) 
            and any(row['is_approved'] is not None for row in livestocks)
        )
    else:
        is_approved = False
        livestocks = BlockData.get_dummy_livestock(village_id=payload['village_id'],
                                            panchayat_id=payload['panchayat_id'],
                                            block_id=payload['block_id'], 
                                            district_id=payload['district_id'])

    return render_template('desktop/demand/livestock.html', 
                           livestock=livestocks, 
                           livestock_data=json.dumps(livestocks), 
                           is_approved=is_approved,
                           breadcrumbs=HelperClass.get_breadcrumbs(payload),
                           menu= HelperClass.get_demand_menu())

@blp.route('/crops', methods=['POST','GET'])
@login_required
def crops():
    if request.method=='POST':
        json_data = request.json
        BlockData.update_crops(json_data, current_user.id)
        flash('Crops Data is Validated/Updated')
        return jsonify({'redirect_url': url_for('.status')})
    session_data = session.get('payload')
    if not session_data:
        return redirect(url_for('mobile.index'))
    else:
        payload = json.loads(session_data)
    crops = BlockData.get_crops_consumption(village_id=payload['village_id'],
                                            panchayat_id = payload['panchayat_id'],
                                            block_id=payload['block_id'], 
                                            district_id=payload['district_id'], 
                                            user_id=current_user.id)
    if crops:
        is_approved = (
            all(row['is_approved'] for row in crops if row['is_approved'] is not None) 
            and any(row['is_approved'] is not None for row in crops)
        )
    else:
        is_approved = False
        crops = BlockData.get_dummy_crops(village_id=payload['village_id'],
                                            panchayat_id = payload['panchayat_id'],
                                            block_id=payload['block_id'], 
                                            district_id=payload['district_id'])
        
    return render_template('desktop/demand/crops.html', 
                           crops=crops, 
                           crops_data=json.dumps(crops), 
                           is_approved=is_approved,
                           breadcrumbs=HelperClass.get_breadcrumbs(payload),
                           menu= HelperClass.get_demand_menu())

@blp.route('/industries', methods=['POST','GET'])
@login_required
def industries():
    if request.method=='POST':
        json_data = request.json
        BlockData.update_industries(json_data, current_user.id)
        flash('Industries Data is Validated/Updated')
        return jsonify({'redirect_url': url_for('.status')})
    session_data = session.get('payload')
    if not session_data:
        return redirect(url_for('mobile.index'))
    else:
        payload = json.loads(session_data)
    industries = BlockData.get_block_industries(village_id=payload['village_id'],
                                            panchayat_id = payload['panchayat_id'],
                                            block_id=payload['block_id'], 
                                            district_id=payload['district_id'], 
                                            user_id=current_user.id)
    if industries:
        is_approved = (
            all(row['is_approved'] for row in industries if row['is_approved'] is not None) 
            and any(row['is_approved'] is not None for row in industries)
        )
    else:
        is_approved = False
        industries = BlockData.get_dummy_industries(village_id=payload['village_id'],
                                            panchayat_id = payload['panchayat_id'],
                                            block_id=payload['block_id'], 
                                            district_id=payload['district_id'])
        
    return render_template('desktop/demand/industry.html', 
                           industries=industries, 
                           industry_data=json.dumps(industries), 
                           is_approved=is_approved,
                           breadcrumbs=HelperClass.get_breadcrumbs(payload),
                           menu= HelperClass.get_demand_menu())

@blp.route('/surface', methods=['POST','GET'])
def surface():
    session_data = session.get('payload')
    if not session_data:
        return redirect(url_for('mobile.index'))
    else:
        payload = json.loads(session_data)
    if request.method=='POST':
        json_data = request.json
        BlockData.update_surface(json_data, current_user.id)
        flash('Surface Water Data is Validated/Updated')
        return jsonify({'redirect_url': url_for('.status')})    
    surface_supply = BlockData.get_surface_supply(village_id=payload['village_id'],
                                            panchayat_id = payload['panchayat_id'],
                                            block_id=payload['block_id'], 
                                            district_id=payload['district_id'], 
                                            user_id=current_user.id)
    if surface_supply:
        is_approved = (
            all(row['is_approved'] for row in surface_supply if row['is_approved'] is not None) 
            and any(row['is_approved'] is not None for row in surface_supply)
        )
    else:
        is_approved = False
        surface_supply = BlockData.get_dummy_surface(village_id=payload['village_id'],
                                            panchayat_id = payload['panchayat_id'],
                                            block_id=payload['block_id'], 

iAndhra/app/templates/desktop/supply/surface.html
{% extends 'desktop/base.html' %}
{% block title %}Surface{% endblock %}
{% from 'mobile/components.html' import table_title, validate_button, input_hidden, floating_input,validation_input,badge %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-8 text-center">
        {{table_title(title='Edit Surface Water Data', subtitle='(in Ha M)')}}
    </div>
    <div class="col">
        {% if is_approved %}
            {{badge()}}
        {% endif %}
    </div>
</div>
<section>
    <div class="overflow-y-scroll" style="height:30vh !important;">    
        <table class="table table-bordered table-sm fs-7 mb-0">
            <thead class="text-center">
                <tr>
                    <th>S.No.</th>
                    <th>Waterbody</th>
                    <th>Count</th>
                    <th>Capacity</th>
                    <th>Update</th>
                </tr>
            </thead>
            <tbody>
                {% for row in waterbodies %}
                <tr>
                    <td class="text-center">{{loop.index}}</td>
                    <td class="text-start">
                        {% if row['waterbody_name']|lower=='whs' %}
                        {{row['waterbody_name'] | upper}}
                        {% else %}
                        {{row['waterbody_name'] | title}}
                        {% endif %}
                       
                        {{input_hidden(name='id', value=row['id'])}}
                    </td>
                    <td class="text-end" id="waterbodyCount">
                        {{row['count']}}
                    </td>
                    <td class="text-end" id="waterbodyStorage">
                        {{row['storage']}}
                    </td>
                    <td class="text-center text-body-secondary">
                        <button class="btn fetch-row-data p-0 fs-7">
                            <i class="fa-solid fa-pen"></i>
                        </button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div> 
    {{validate_button(is_approved=is_approved)}}
</section>
<section>
    {{floating_input(label='Waterbody', placeholder='', input_id='wb_name', input_type='text', isdisabled='true' )}}
    {{validation_input(label = 'Enter Waterbody Count',id = 'wb_count',type='number',valid = 'Looks Good!',invalid = 'Must be a whole number',min='0')}}
    {{validation_input(label = 'Enter Waterbody Storage',id = 'wb_storage',type='number',valid = 'Looks Good!',invalid = 'Must be a whole number',min='0')}}
    <div class="text-end">
        <button class="btn btn-outline-dark btn-sm me-2" id="btnBack">Back</button>
        <button class="btn btn-dark btn-sm" id="btnUpdate" disabled>Update</button>
    </div>  
</section>
<input type="hidden" name="waterbody_data" id="waterbodyData" value="{{waterbody_data}}">
<input type="hidden" name="post_url" id="postUrl" value="{{url_for('desktop.surface')}}">
{% endblock %}
{% block scripts %}
<script>

// Elements
const sectionTable = document.querySelector("section:first-of-type");
const sectionInput = document.querySelector("section:last-of-type");
const btnBack = document.getElementById("btnBack");
const btnUpdate = document.getElementById("btnUpdate");
const btnSubmit = document.getElementById("btn_submit");
const chkDeclare = document.getElementById("chkDeclare");
const categoryInput = document.getElementById("wb_name");
const populationInput = document.getElementById("wb_count");
const storageInput = document.getElementById("wb_storage");
const postUrl = document.getElementById("postUrl").value;

// Waterbody array
let waterbody = JSON.parse(document.getElementById('waterbodyData').value);

let currentRowId = null; // Tracks the currently edited row

// On page load, set initial visibility and button states
document.addEventListener("DOMContentLoaded", () => {
    sectionTable.classList.remove("visually-hidden");
    sectionInput.classList.add("visually-hidden");

    // Enable/disable the checkbox and submit button based on `is_approved`
    const isAnyNotApproved = waterbody.some(row => !row.is_approved);
    if (chkDeclare) { chkDeclare.disabled = !isAnyNotApproved; }
    // btnSubmit.disabled = isAnyNotApproved;
});

// Event listener for edit buttons
document.querySelectorAll(".btn.fetch-row-data").forEach(button => {
    button.addEventListener("click", function (event) {
        event.preventDefault();
        toggleSpinner();

        // Get row data using hidden inputs
        const row = this.closest("tr");
        const rowId = parseInt(row.querySelector('input[name="id"]').value, 10);
        const waterbodyRow = waterbody.find(h => h.id === rowId);

        // Populate input fields in the form
        currentRowId = rowId;
        categoryInput.value = waterbodyRow.waterbody_name;
        populationInput.value = waterbodyRow.count;
        storageInput.value = waterbodyRow.storage

        // Switch sections
        sectionTable.classList.add("visually-hidden");
        sectionInput.classList.remove("visually-hidden");
        toggleSpinner();
    });
});

// Back button event
btnBack.addEventListener("click", function (event) {
    event.preventDefault();
    toggleSpinner();

    // Reset currentRowId and switch sections
    currentRowId = null;
    resetValidationState();
    sectionInput.classList.add("visually-hidden");
    sectionTable.classList.remove("visually-hidden");
    toggleSpinner();
});

// Update button event
btnUpdate.addEventListener("click", function (event) {
    event.preventDefault();
    toggleSpinner();

    if (currentRowId !== null) {
        // Update the waterbody array
        const updatedCount = parseInt(populationInput.value, 10);
        const updatedStorage = parseFloat(storageInput.value, 10);
        const waterbodyRow = waterbody.find(h => h.id === currentRowId);

        // Store the original value if not already stored
        if (!waterbodyRow.hasOwnProperty("original_count")) {
            waterbodyRow.original_count = waterbodyRow.count; // Store the initial count value
        }

        // Store the original value if not already stored
        if (!waterbodyRow.hasOwnProperty("original_storage")) {
            waterbodyRow.original_storage = waterbodyRow.storage; // Store the initial count value
        }
        // Update the count in the waterbody array
        waterbodyRow.count = updatedCount;
        waterbodyRow.storage = updatedStorage;

        // Update the table row
        const row = document.querySelector(`tr input[value="${currentRowId}"]`).closest("tr");
        const countCell = row.querySelector("#waterbodyCount");
        const storageCell = row.querySelector("#waterbodyStorage");

        // Compare the updated count with the original count and apply/remove 'text-danger'
        if (updatedCount !== waterbodyRow.original_count) {
            countCell.textContent = updatedCount;
            countCell.classList.add("text-danger");
        } else {
            countCell.textContent = updatedCount;
            countCell.classList.remove("text-danger");
        }
        // Compare the updated storage with the original storage and apply/remove 'text-danger'
        if (updatedStorage !== waterbodyRow.original_storage) {
            storageCell.textContent = updatedStorage;
            storageCell.classList.add("text-danger");
        } else {
            storageCell.textContent = updatedStorage;
            storageCell.classList.remove("text-danger");
        }

        // Reset and switch sections
        currentRowId = null;
        resetValidationState();
        sectionInput.classList.add("visually-hidden");
        sectionTable.classList.remove("visually-hidden");
    }
    toggleSpinner();
});


// Checkbox change event
if (chkDeclare){
    chkDeclare.addEventListener("change", function () {
        btnSubmit.disabled = !this.checked;
    });
}

// Submit button event
btnSubmit.addEventListener("click", (event) => {
    event.preventDefault();
    toggleSpinner();

    // Post updated waterbody array to the server
    fetch(postUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(waterbody)
    }).then(response => {
        if (!response.ok) {
            toggleSpinner();
            throw new Error(`HTTP error! Status: ${response.status}`);
        }
        return response.json(); // Parse JSON response
    })
    .then(data => {
        if (data.redirect_url) {
            toggleSpinner();
            window.location.href = data.redirect_url; // Redirect to the URL provided
        } else {
            alert("No redirect URL provided.");
        }
    }).catch(error => {
        toggleSpinner();
        console.error("Error submitting data:", error);
        alert("An error occurred while submitting data.");
    });
});


function resetValidationState() {
    const inputs = document.querySelectorAll('input, select');
    inputs.forEach(input => {
        const validFeedback = input.parentElement.querySelector('.valid-feedback');
        const invalidFeedback = input.parentElement.querySelector('.invalid-feedback');
        if (validFeedback) validFeedback.style.display = 'none';
        if (invalidFeedback) invalidFeedback.style.display = 'none';
        input.classList.remove('is-valid', 'is-invalid');
        btnUpdate.disabled = true;
    });
}

(() => {
  'use strict'

  // Fetch all the forms we want to apply custom Bootstrap validation styles to
  const forms = document.querySelectorAll('.needs-validation')

  // Loop over them and prevent submission
  Array.from(forms).forEach(form => {
    form.addEventListener('submit', event => {
      if (!form.checkValidity()) {
        event.preventDefault()
        event.stopPropagation()
      }

      form.classList.add('was-validated')
    }, false)
  });

  // Real-time validation
  const inputs = document.querySelectorAll('input, select');

// Attach real-time validation to all input/select fields
inputs.forEach(input => {
    input.addEventListener('input', () => validateField(input));
    input.addEventListener('change', () => validateField(input));
});

function validateField(input) {
    const validFeedback = input.parentElement.querySelector('.valid-feedback');
    const invalidFeedback = input.parentElement.querySelector('.invalid-feedback');
    btnUpdate.disabled = false;
    if (input.checkValidity()) {
        validFeedback.style.display = 'block';
        invalidFeedback.style.display = 'none';
        input.classList.remove('is-invalid');
        input.classList.add('is-valid');
    } else {
        validFeedback.style.display = 'none';
        invalidFeedback.style.display = 'block';
        input.classList.remove('is-valid');
        input.classList.add('is-invalid');
    }
}
})()

</script>
{% endblock %}