iAuth/app/routes/auth.py
from flask import jsonify,request,redirect,url_for,flash,render_template,session,make_response
from flask.views import MethodView
from flask_jwt_extended import create_access_token, create_refresh_token, jwt_required,set_access_cookies,unset_access_cookies
from flask_smorest import Blueprint, abort
from iAuth.app.models.user import UserModel as User
from passlib.hash import pbkdf2_sha256
from flask_login import current_user, login_required, login_user, logout_user
from iAuth.app.routes.email_helper import *
from iAuth.app.models.inrole import inRoleModel
import uuid
import requests

blp = Blueprint("admin", "admin", description="User Authentication")

BASE_URL = 'https://training.wasca.in'
@blp.route('/profile')
def profile():
    return('profile')


@blp.route('/get_auth_json')
def get_auth_json():
    session_id = session.get('session_id', None)  # Will return None if 'session_id' is not in the session
    user_id = session.get('user_id', None)   
    if user_id and session_id:
        return jsonify({'message':'logged in','user_id':user_id,'session_id':session_id})
    else:
        return jsonify({'message':'Not Authenticated'})
    



# Route for login
@blp.route('/login', methods=["POST", "GET"])
def login():
    if request.method == "POST":
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()       
        if user:
            db_email = user.email
            db_pass = user.password
            hash_check = pbkdf2_sha256.verify(password, db_pass)        
            if db_email == email and hash_check:
                login_user(user)
                session['user_id'] = user.id
                session_id = (uuid.uuid4())
                session['session_id'] = session_id
                return redirect('/')
                
                # return {"message":"Error generating JWT Token"}
            else:
                flash('Incorrect Credentials.')
                return redirect(url_for('admin.login'))
        else:
            flash('No Records Found !! Please validate your Credentials.')
            return redirect(url_for('admin.login'))
        
    return render_template('login.html')

# Route for user registration
@blp.route('/register', methods=["POST", "GET"])
def register():
    if request.method == "POST":
        email = request.form.get('email')
        name = request.form.get('username')
        password = pbkdf2_sha256.hash(request.form.get('password'))
        if email and name and password:

            user = User.get_user_by_email(email)
            if user:
                flash('Email address already exists')
                return redirect(url_for('admin.register'))

            user = User(name, email, password)
            session['user_email'] = email
            session['user_password'] = password
            session['user_name'] = name
            
            otp_details = send_email(email)
            
            if otp_details:
                session['otp_details'] = otp_details
                otp_message = f"Email has been sent to {email} Successfully. Please check your inbox (and spam folder) for the OTP."
                flash(otp_message)
                return redirect(url_for('admin.verify_otp'))

            else:
                flash("Email cannot be sent. Please try again later.")
                return redirect(url_for('admin.register'))
            
        
        else:
            return redirect(url_for('admin.register'))

    return render_template('register.html')


# Route for OTP verification
@login_required
@blp.route('/verify_otp', methods=["POST", "GET"])
def verify_otp():
    if request.method == "POST":
        name = session.get('user_name')
        password = session.get('user_password')
        email = session.get('user_email')
        otp_details = session.get('otp_details')
        otp_entered = request.form.get('otp')
        otp_generated = otp_details['otp']
        
        if int(otp_generated) == int(otp_entered):
            user = User(name, email, password)
            user.save_to_db()
            user_db = User.find_by_username(name)
            user_id = user_db['id']
            role_id = 1
            inrole = inRoleModel(user_id,role_id)
            inrole.save_to_db()
            
            flash("OTP Verified Successfully. Please login to continue")
            return redirect(url_for('admin.login'))
        else:
            flash("OTP cannot be verified. Please enter valid OTP")
            return redirect(url_for('admin.verify_otp'))
    return render_template('verify_otp.html')

# Route to resend OTP
@login_required
@blp.route('/resend_otp')
def resend_otp():
    email = session.get('user_email')
    otp_details = send_email(email)
            
    if otp_details:
        session['otp_details'] = otp_details
        otp_message = f"Email has been sent to {email}. Please check your inbox (and spam folder) for the OTP."
        flash(otp_message)
        return redirect(url_for('admin.verify_otp'))

    else:
        flash("Email cannot be sent. Please try again later.")
        return redirect(url_for('admin.verify_otp'))

# Route for logout
@blp.route('/logout')
@login_required
def logout():
    logout_user()
    session.pop('session_id', None)  # 'None' ensures no error if key is absent
    session.pop('user_id', None)
    session['logged_out'] = True
    # Redirect to login page or any other URL
    # Clear the JWT cookie
    return redirect(url_for('admin.login'))

# Route for changing password
@blp.route('/change_password/<id>', methods=['GET', 'POST'])
@login_required
def change_password(id):

    if request.method == "POST":
            
        current_pwd = request.form.get('old_pass')
        new_pass = pbkdf2_sha256.hash(request.form.get('new_pass'))

        user = User.query.filter_by(id=id).first()       
        if user:
        
            db_pass = user.password
            hash_check = pbkdf2_sha256.verify(current_pwd, db_pass)        
            if hash_check:
                data = {"password": new_pass}
                User.update_db(data, id)
                logout_user()
                session['logged_out'] = True   
                flash('Password Changed Successfully. Please login with new password to continue')
                return redirect(url_for('admin.login'))
            
            else:
                flash('Please Check Your Old Password and Try Again !! ')
                return redirect(url_for('admin.change_password', id=id))
    
    if request.method == "GET":
        return render_template('change_password.html')

# Route for verifying email
@login_required
@blp.route('/verify_email', methods=["POST", "GET"])
def verify_email():
    if request.method == "POST":
        new_pass = session.get('new_pass')
        otp_details = session.get('otp_details')
        otp_entered = request.form.get('otp')
        otp_generated = otp_details['otp']
        
        if int(otp_generated) == int(otp_entered):
            data = {"password": new_pass}
            User.update_db(data, current_user.id)   
            logout_user()
            session['logged_out'] = True
            flash("OTP Verified Successfully. Please login with new password continue")
            return redirect(url_for('admin.login'))
        else:
            flash("OTP cannot be verified. Please enter valid OTP")
            return redirect(url_for('admin.verify_email'))
    return render_template('verify_email.html')

# Route for resetting password
@login_required
@blp.route('/reset_password/<id>', methods=['POST', 'GET'])
def reset_password(id):
    if request.method == "GET":
        return render_template('reset_password.html')
    else:
        user = User.query.filter_by(id=id).first()
        new_pass = pbkdf2_sha256.hash(request.form.get('new_pass'))
        session['new_pass'] = new_pass
        email = user.email
        otp_details = send_email(email)
            
        if otp_details:
            session['otp_details'] = otp_details
            otp_message = f"OTP has been sent to registered email Successfully. Please check your inbox (and spam folder) for the OTP."
            flash(otp_message)
            return redirect(url_for('admin.verify_email'))

        else:
            flash("Email cannot be sent. Please try again later.")
            return redirect(url_for('admin.register'))

# Route for the page that doesn't require login
@blp.route('/no_login')
def no_login():
    return render_template('no_login.html')  # Rendering no_login.html template

@blp.route('/admin')
def admin():
    return render_template('admin.html')

iAuth/app/routes/index.py
from flask_smorest import Blueprint
from flask import render_template

blp = Blueprint('dashboard','dashboard')

@blp.route('/')
def hello_world():
    return render_template('index.html')

@blp.route('/get_page')
def new():
    return render_template('admin_base.html')

iAuth/app/templates/admin_base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>iApps - {% block title %}{% endblock %} </title>
	<!-- As a link -->
	<link rel="stylesheet" href="https://bootswatch.com/5/lux/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
		integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
		crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="{{ url_for('static', filename='css/style_new.css') }}" />
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
		integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
	<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
		integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
	<script type="text/javascript" src="http://maps.stamen.com/js/tile.stamen.js?v1.2.3"></script>
	<meta name="theme-color" content="transparent" />
	{% block css %}
	{% endblock %}
</head>

<body>

	{% block content %}
	<nav class="navbar bg-primary py-1">
		<div class="container-fluid">
			<div class="row p-0 m-0" style="width: 100%;">
				<div class="col-auto p-0 me-auto align-self-center">
					<a class="navbar-brand text-white fs-6" href="{{url_for('dashboard.hello_world')}}">
						<span class="text-warning">i</span>Auth</a>
				</div>
				<div class="col-auto">
					<div class="row">
						<div class="col dropdown p-0">
							<button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown"
								aria-expanded="false">
								<i class="fa-solid fa-user fa-lg" style="color: white;"></i>
							</button>
							<ul class="dropdown-menu">
								{%if current_user.is_authenticated%}
									
								<li><a class="dropdown-item" href="{{url_for('admin.admin')}}">Admin</a></li>
								<li><a class="dropdown-item" href="{{url_for('admin.profile')}}">Profile</a></li>
								<li><a class="dropdown-item" href="{{url_for('admin.change_password',id = current_user.id)}}">Change Pwd</a></li>
								<li><a class="dropdown-item" href="{{url_for('admin.logout')}}">Logout</a></li>
								{%else%}
								<li><a class="dropdown-item" href="{{url_for('admin.login')}}">Login</a></li>
								<li><a class="dropdown-item" href="{{url_for('admin.register')}}">Register</a></li>
								{%endif%}
							</ul>
						</div>

						<div class="col align-self-center p-0">
							<button class="navbar-toggler py-0 px-1" type="button" data-bs-toggle="offcanvas"
								data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar"
								aria-label="Toggle navigation">
								<span class="navbar-toggler-icon"></span>
							</button>
						</div>

					</div>
				</div>
			</div>



			<div class="offcanvas offcanvas-start offcanvas-size-sm" tabindex="-1" id="offcanvasNavbar"
				aria-labelledby="offcanvasNavbarLabel">
				<div class="offcanvas-header">
					<h5 class="offcanvas-title font-monotype" id="offcanvasNavbarLabel">
						<span class="text-danger">i</span>Water
					</h5>
					<button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
				</div>
				<div class="offcanvas-body">
					<ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
						<li class="nav-item">
							<a class="nav-link active" aria-current="page" href="{{url_for('admin.login')}}">Login</a>
						</li>
				</div>
			</div>
		</div>
	</nav>
	{% endblock %}

	<!-- Compiled and minified JavaScript -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
	{% block script %}{% endblock %}
</body>

</html>

iAuth/app/templates/change_password.html
{%extends 'admin_base.html'%}
{% block title %}
Account - Change Password
{%endblock%}
{%block content%}
{{super()}}

<div class="container mt-3">
    <div class="card my-2 shadow-sm">
        <div class="card-header text-center fw-bold py-1">
            <div class="fs-6 fw-bold mb-0">Change Password</div>
        </div>
        <div class="card-body justify-content-center pt-2 p-1">
            <div class="row m-0" style="width: 100%;">
                <div class="col">
                    <div class="container p-1">
                        {% with messages = get_flashed_messages() %}
                        {% if messages %}
                        <div class="alert alert-{%if 'Successfully' in messages[0]%}success{%else%}danger{%endif%} text-center" role="alert">
                            {{ messages[0] }}
                        </div>
                        {% endif %}
                        {% endwith %}
                        <form action="{{url_for('admin.change_password',id = current_user.id)}}" method="post">
                            <fieldset>

                                <div>
                                    <input type="password" class="form-control mt-2" id="old_pass"
                                        aria-describedby="emailHelp" name="old_pass" placeholder="Enter Old Password">
                                </div>
                                <div>
                                    <input type="password" class="form-control mt-2" id="new_pass"
                                        aria-describedby="emailHelp" name="new_pass" placeholder="Enter New Password">
                                </div>
                                <div>
                                    <input type="password" class="form-control mt-2" id="new_pass_2"
                                        aria-describedby="emailHelp" name="new_pass_2" placeholder="Enter New Password Again">
                                </div>
                                
                                <div class="row">
                                    
                                    <button type="submit" class="btn btn-primary mt-3 form-size">Change Password</button>
                                    <p class="text-center text-secondary mt-1">Forgot Password? <a href="{{url_for('admin.reset_password',id = current_user.id)}}"></a></p>
                                </div>
                                
                            </fieldset>
                        </form>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>


{%endblock%}

iAuth/app/templates/login.html
{%extends 'admin_base.html'%}
{% block title %}
Account - Login
{%endblock%}
{%block content%}
{{super()}}

<div class="container mt-3">
    <div class="card my-2 shadow-sm">
        <div class="card-header text-center fw-bold py-1">
            <div class="fs-6 fw-bold mb-0">Login</div>
            <div class="fs-7 fw-normal text-center text-secondary mt-n4">Login to access content</div>
        </div>
        <div class="card-body justify-content-center pt-2 p-1">
            <div class="row m-0" style="width: 100%;">
                <div class="col">
                    <div class="container p-1">
                        {% with messages = get_flashed_messages() %}
                        {% if messages %}
                        <div class="alert alert-{% if 'Successfully' in messages[0] %}success{%else%}danger{%endif%} text-center" role="alert">
                        {{ messages[0] }}
                        </div>
                        {% endif %}
                        {% endwith %}
                        <form action="{{url_for('admin.login')}}" method="post">
                            <fieldset>

                                <div>
                                    <input type="email" class="form-control mt-2" id="exampleInputEmail1"
                                        aria-describedby="emailHelp" name="email" placeholder="Enter email">
                                </div>
                                <div>
                                    <input type="password" class="form-control mt-2" id="exampleInputPassword1"
                                        placeholder="Password" name="password" autocomplete="off">
                                </div>
                                <div class="row justify-content-center mx-1 mt-3">
                                    <button type="submit" class="btn btn-primary">Login</button>
                                    <p class="text-secondary text-center mt-1">Not a member yet? <a href="{{url_for('admin.register')}}">Register</a></p>
                                </div>
                                
                            </fieldset>
                        </form>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>


{%endblock%}

iAuth/app/templates/register.html
{%extends 'admin_base.html'%}
{% block title %}
Account - Register
{%endblock%}
{%block content%}
{{super()}}

<div class="container mt-3">
    <div class="card my-2 shadow-sm">
        <div class="card-header text-center fw-bold py-1">
            <div class="fs-6 fw-bold mb-0">Register</div>
            <div class="fs-7 fw-normal text-center text-secondary mt-n4">Register to access content</div>
        </div>
        <div class="card-body justify-content-center pt-2 p-1">
            <div class="row m-0" style="width: 100%;">
                <div class="col">
                    <div class="container p-1">
                        {% with messages = get_flashed_messages() %}
                        {% if messages %}
                        <div class="alert alert-danger text-center" role="alert">
                            {{ messages[0] }}. Go to <a href="{{ url_for('admin.login') }}">Login Page</a>.
                        </div>
                        {% endif %}
                        {% endwith %}
                        <form action="{{url_for('admin.register')}}" method="post">
                            <fieldset>
                                <div>
                                    <input type="text" class="form-control mt-2" id="username"
                                        aria-describedby="emailHelp" name="username" placeholder="Enter Username">
                                </div>
                                <div>
                                    <input type="email" class="form-control mt-2" id="exampleInputEmail1"
                                        aria-describedby="emailHelp" name="email" placeholder="Enter email">
                                </div>
                                <div>
                                    <input type="password" class="form-control mt-2" id="exampleInputPassword1"
                                        placeholder="Password" name="password" autocomplete="off">
                                </div>
                                <div>
                                    <input type="password" class="form-control mt-2" id="exampleInputPassword1"
                                        placeholder="Confirm Password" name="password-1" autocomplete="off">
                                </div>
                                <div class="row justify-content-center mx-1 mt-3">
                                    <button type="submit" class="btn btn-primary">Register</button>
                                    <p class="text-secondary text-center mt-1">Already a member? <a href="{{url_for('admin.login')}}" >Login</a></p>

                                </div>
                                
                            </fieldset>
                        </form>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>


{%endblock%}

iAuth/app/templates/reset_password.html
{%extends 'admin_base.html'%}
{% block title %}
Account - Reset Password
{%endblock%}
{%block content%}
{{super()}}

<div class="container mt-3">
    <div class="card my-2 shadow-sm">
        <div class="card-header text-center fw-bold py-1">
            <div class="fs-6 fw-bold mb-0">Reset Password</div>
        </div>
        <div class="card-body justify-content-center pt-2 p-1">
            <div class="row m-0" style="width: 100%;">
                <div class="col">
                    <div class="container p-1">
                        {% with messages = get_flashed_messages() %}
                        {% if messages %}
                        <div class="alert alert-{%if 'Successfully' in messages[0]%}success{%else%}danger{%endif%} text-center" role="alert">
                            {{ messages[0] }}
                        </div>
                        {% endif %}
                        {% endwith %}
                        <form action="{{url_for('admin.reset_password',id = current_user.id)}}" method="post">
                            <fieldset>

                                
                                <div>
                                    <input type="password" class="form-control mt-2" id="new_pass"
                                        aria-describedby="emailHelp" name="new_pass" placeholder="Enter New Password">
                                </div>
                                <div>
                                    <input type="password" class="form-control mt-2" id="new_pass_2"
                                        aria-describedby="emailHelp" name="new_pass_2" placeholder="Enter New Password Again">
                                </div>
                                
                                <div class="row">
                                    
                                    <button type="submit" class="btn btn-primary mt-3 form-size">Reset Password</button>
                                </div>
                                
                            </fieldset>
                        </form>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>


{%endblock%}

iAuth/app/templates/verify_email.html
{%extends 'admin_base.html'%}
{% block title %}
Account - Verify OTP
{%endblock%}
{%block content%}
{{super()}}

<div class="container mt-3">
    <div class="card my-2 shadow-sm">
        <div class="card-header text-center fw-bold py-1">
            <div class="fs-6 fw-bold mb-0">Verify OTP</div>
        </div>
        <div class="card-body justify-content-center pt-2 p-1">
            <div class="row m-0" style="width: 100%;">
                <div class="col">
                    <div class="container p-1">
                        {% with messages = get_flashed_messages() %}
                        {% if messages %}
                        <div class="alert alert-{% if 'cannot' in messages[0] %}danger{%else%}success{%endif%} text-center" role="alert">
                        {{ messages[0] }}
                        </div>
                        {% endif %}
                        {% endwith %}
                        <form action="{{url_for('admin.verify_email')}}" method="post">
                            <fieldset>

                                <div>
                                    <input type="text" class="form-control mt-2" id="exampleInputEmail1"
                                        aria-describedby="emailHelp" name="otp" placeholder="Enter OTP">
                                </div>
                                
                                <div class="row">
                                    <div class="btn-toolbar justify-content-center" role="toolbar" aria-label="Toolbar with button groups">
                                        <div class="btn-group me-2" role="group" aria-label="First group">
                                            <a id="resendLink"><button type="button" id="resendButton" class="btn btn-secondary mt-3 form-size" disabled>Resend OTP</button></a>
                                        </div>&nbsp;&nbsp;&nbsp;&nbsp;
                                        <div class="btn-group me-2" role="group" aria-label="First group">
                                            <button type="submit" class="btn btn-primary mt-3 form-size">Verify OTP</button>
                                        </div>
                                    </div>
                                </div>
                                
                            </fieldset>
                        </form>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>


{%endblock%}
{% block script %}
<script>
    // Function to start the countdown timer
    function startTimer(duration, button, anchor) {
        var timer = duration;
        button.setAttribute("disabled", "true"); // Disable the button initially
        var interval = setInterval(function () {
            button.textContent = "Resend OTP in " + timer + " sec";
            if (--timer < 0) {
                clearInterval(interval);
                button.removeAttribute("disabled"); // Enable the button when timer ends
                button.textContent = "Resend OTP";
                anchor.setAttribute("href", "{{url_for('admin.resend_otp')}}"); // Add URL to anchor
            }
        }, 1000);
    }

    window.onload = function () {
    // For desktop
    var button = document.getElementById('resendButton');
    var anchor = document.getElementById('resendLink');
    var twoMinutes = 120;
    startTimer(twoMinutes, button, anchor);
    
};
</script>
{%endblock%}

iAuth/app/templates/verify_otp.html
{%extends 'admin_base.html'%}
{% block title %}
Account - Verify OTP
{%endblock%}
{%block content%}
{{super()}}

<div class="container mt-3">
    <div class="card my-2 shadow-sm">
        <div class="card-header text-center fw-bold py-1">
            <div class="fs-6 fw-bold mb-0">Verify OTP</div>
        </div>
        <div class="card-body justify-content-center pt-2 p-1">
            <div class="row m-0" style="width: 100%;">
                <div class="col">
                    <div class="container p-1">
                        {% with messages = get_flashed_messages() %}
                        {% if messages %}
                        <div class="alert alert-{% if 'cannot' in messages[0] %}danger{%else%}success{%endif%} text-center" role="alert">
                        {{ messages[0] }}
                        </div>
                        {% endif %}
                        {% endwith %}
                        <form action="{{url_for('admin.verify_otp')}}" method="post">
                            <fieldset>

                                <div>
                                    <input type="text" class="form-control mt-2" id="exampleInputEmail1"
                                        aria-describedby="emailHelp" name="otp" placeholder="Enter OTP">
                                </div>
                                
                                <div class="row">
                                    <div class="btn-toolbar justify-content-center" role="toolbar" aria-label="Toolbar with button groups">
                                        <div class="btn-group me-2" role="group" aria-label="First group">
                                            <a id="resendLink"><button type="button" id="resendButton" class="btn btn-secondary mt-3 form-size" disabled>Resend OTP</button></a>
                                        </div>&nbsp;&nbsp;&nbsp;&nbsp;
                                        <div class="btn-group me-2" role="group" aria-label="First group">
                                            <button type="submit" class="btn btn-primary mt-3 form-size">Verify OTP</button>
                                        </div>
                                    </div>
                                </div>
                                
                            </fieldset>
                        </form>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>


{%endblock%}
{% block script %}
<script>
    // Function to start the countdown timer
    function startTimer(duration, button, anchor) {
        var timer = duration;
        button.setAttribute("disabled", "true"); // Disable the button initially
        var interval = setInterval(function () {
            button.textContent = "Resend OTP in " + timer + " sec";
            if (--timer < 0) {
                clearInterval(interval);
                button.removeAttribute("disabled"); // Enable the button when timer ends
                button.textContent = "Resend OTP";
                anchor.setAttribute("href", "{{url_for('admin.resend_otp')}}"); // Add URL to anchor
            }
        }, 1000);
    }

    window.onload = function () {
    // For desktop
    var button = document.getElementById('resendButton');
    var anchor = document.getElementById('resendLink');
    var twoMinutes = 120;
    startTimer(twoMinutes, button, anchor);
    
};
</script>
{%endblock%}