iAndhra/app/routes/mobile.py
from flask import Blueprint, json, jsonify, make_response, redirect, render_template, request, session, url_for
from flask_login import current_user

from iAndhra.app.classes.block_or_census import BlockOrCensus
from iAndhra.app.classes.budget_data import BudgetData
from iAndhra.app.models import TerritoryJoin
from iAndhra.app.models.districts import District
from iAndhra.app.models.villages import Village


blp = Blueprint("mobile","mobile")

@blp.route('/')
def splash():
    return render_template("splash_screen.html")

@blp.route('/index', methods=['POST','GET'])
def index():
    if request.method == 'POST':
        json_data = request.json
        if 'payload' in session:
            session['payload'] = ''
        json_data['district_short_name'] = District.get_short_name(int(json_data['district_id']))
        payload = json.dumps(json_data)
        session['payload'] = payload
        if current_user.is_authenticated:
            return json.dumps(url_for('desktop.status'))
        return json.dumps(url_for('.home'))
    if current_user.is_authenticated:
        if current_user.isAdmin:
            districts = TerritoryJoin.get_districts()
        else:
            districts = District.get_districts_by_id(current_user.district_id)
    else:
        districts = TerritoryJoin.get_districts()
    return render_template("mobile/index.html", districts=districts)

@blp.route("/villages", methods=['POST'])
def villages():
    json_data = request.json
    if json_data is not None:
        panchayat_id = int(json_data['panchayat_id'])
    else:
        return make_response('', 400)
    villages = TerritoryJoin.get_villages(panchayat_id)
    if villages:
        return villages
    else:
        return make_response('', 400)

@blp.route("/panchayats", methods=['POST'])
def panchayats():
    json_data = request.json
    if json_data is not None:
        block_id = int(json_data['block_id'])
    else:
        return make_response('', 400)
    panchayats = TerritoryJoin.get_panchayats(block_id)
    if current_user.is_authenticated:
        if not current_user.isAdmin:
            filtered_panchayats = [panchayat for panchayat in panchayats if panchayat['id'] == current_user.panchayat_id]
            return filtered_panchayats
    if panchayats:
        return panchayats
    else:
        return make_response('', 400)
    
@blp.route("/blocks", methods=['POST'])
def blocks():
    json_data = request.json
    if json_data is not None:
        district_id = int(json_data['district_id'])
    else:
        return make_response('', 400)
    blocks = TerritoryJoin.get_blocks(district_id)
    if current_user.is_authenticated:
        if not current_user.isAdmin:
            filtered_blocks = [block for block in blocks if block['id'] == current_user.block_id]
            return filtered_blocks
    if blocks:
        return blocks
    else:
        return make_response('', 400)


@blp.route('/home')
def home():
    payload = session.get('payload')
    if not payload:
        return redirect(url_for('.index'))
    else:
        payload = json.loads(payload)
    demand_side = BlockOrCensus.get_demand_side_data(payload['village_id'],payload['panchayat_id'],payload['block_id'], payload['district_id'])
    supply_side = BlockOrCensus.get_supply_side_data(payload['village_id'],payload['panchayat_id'],payload['block_id'], payload['district_id'])
    budget = BlockOrCensus.get_water_budget_data(payload['village_id'],payload['panchayat_id'],payload['block_id'], payload['district_id'])
    budget_data = []
    budget_data.append(demand_side)
    budget_data.append(supply_side)
    budget_data.append(budget)
    return render_template("mobile/home.html", 
                           breadcrumbs = get_breadcrumbs(payload),
                           demand_side = budget_data[0],
                           supply_side = budget_data[1],
                           water_budget = budget_data[2],
                           menu = get_main_menu(),
                           chart_data = json.dumps(budget_data),
                           toggle_labels=['chart', 'table'])

# @blp.route('/home')
# def home():
#     payload = session.get('payload')
#     if not payload:
#         return redirect(url_for('.index'))
#     else:
#         payload = json.loads(payload)
#     demand_side = BudgetData.get_demand_side(payload['block_id'], payload['district_id'])
#     supply_side = BudgetData.get_supply_side(payload['block_id'], payload['district_id'], payload['state_id'])
#     budget = BudgetData.get_water_budget(payload['block_id'], payload['district_id'], payload['state_id'])
#     budget_data = []
#     budget_data.append(demand_side)
#     budget_data.append(supply_side)
#     budget_data.append(budget)
#     return render_template("mobile/home.html", 
#                            breadcrumbs = get_breadcrumbs(payload),
#                            demand_side = budget_data[0],
#                            supply_side = budget_data[1],
#                            water_budget = budget_data[2],
#                            menu = get_main_menu(),
#                            chart_data = json.dumps(budget_data),
#                            toggle_labels=['chart', 'table'])

@blp.route('/human')
def human():
    payload = session.get('payload')
    if not payload:
        return redirect(url_for('.index'))
    else:
        payload = json.loads(payload)
    human, is_approved = BlockOrCensus.get_human_data(payload['village_id'],payload['panchayat_id'],payload['block_id'],payload['district_id'])
    return render_template('mobile/demand/human.html',
        is_approved = is_approved, 
        source='Census 2011',
        human = human,
        chart_data= json.dumps(human),
        toggle_labels= ['chart', 'table'],
        breadcrumbs= get_breadcrumbs(payload), 
        menu= get_demand_menu())
# @blp.route('/human')
# def human():
#     """
#     Handle human demand route.
#     """
#     return render_demand_template(
#         "mobile/demand/human.html",
#         demand_function=BudgetData.get_human_consumption,
#         template_data_key='human'
    # )

@blp.route('/livestocks')
def livestocks():
    payload = session.get('payload')
    if not payload:
        return redirect(url_for('.index'))
    else:
        payload = json.loads(payload)
    livestock, is_approved = BlockOrCensus.get_livestock_data(payload['village_id'],payload['panchayat_id'],payload['block_id'],payload['district_id'])  
    return render_template('mobile/demand/livestocks.html',
        is_approved = is_approved, 
        source = 'Livestock Census 2019',
        livestocks = livestock,
        chart_data= json.dumps(livestock),
        toggle_labels= ['chart', 'table'],
        breadcrumbs= get_breadcrumbs(payload), 
        menu= get_demand_menu())  
# @blp.route('/livestocks')
# def livestocks():
#     return render_demand_template(
#         "mobile/demand/livestocks.html",
#         demand_function=BudgetData.get_livestock_consumption,
#         template_data_key='livestocks'
#     )

@blp.route('/crops')
def crops():
    payload = session.get('payload')
    if not payload:
        return redirect(url_for('.index'))
    else:
        payload = json.loads(payload)
    crops, is_approved = BlockOrCensus.get_crop_data(payload['village_id'],payload['panchayat_id'],payload['block_id'],payload['district_id']) 
    return render_template('mobile/demand/crops.html',
        is_approved = is_approved, 
        source = 'Crop Census 2019 (DES)', #https://data.desagri.gov.in/website/crops-apy-report-web
        crops = crops,
        chart_data= json.dumps(crops),
        toggle_labels= ['chart', 'table'],
        breadcrumbs= get_breadcrumbs(payload), 
        menu= get_demand_menu())

# @blp.route('/crops')
# def crops():
#     return render_demand_template(
#         "mobile/demand/crops.html",
#         demand_function=BudgetData.get_crops_consumption,
#         template_data_key='crops'
#     )

@blp.route('/industry')
def industry():
    payload = session.get('payload')
    if not payload:
        return redirect(url_for('.index'))
    else:
        payload = json.loads(payload)
    industry_demand, is_approved = BlockOrCensus.get_industry_data(payload['village_id'],payload['panchayat_id'],payload['block_id'], payload['district_id'])
    has_value = sum(item['count'] for item in industry_demand)
    if is_approved:
            source = 'The Industrial Water demand is reported nil by the block' 
    else:
        source = 'The Industrial Water demand is reported nil by the block' if has_value else 'Industry demand input is awaited.'
    return render_template("mobile/demand/industry.html",
                        subtitle = '(in Ha M)' if is_approved else 'There are no industry in this block',
                        industries = industry_demand if has_value else None, 
                        source = source,
                        is_approved = is_approved,
                        chart_data = json.dumps(industry_demand),
                        breadcrumbs= get_breadcrumbs(payload), 
                        menu= get_demand_menu(),
                        toggle_labels=['chart', 'table'])


# @blp.route('/industry')
# def industry():
#     payload = session.get('payload')
#     if not payload:
#         return redirect(url_for('.index'))
#     else:
#         payload = json.loads(payload)
#     industry_demand = BudgetData.get_industry_demand(payload['block_id'], payload['district_id'], payload['state_id'])
#     has_value = sum(item['count'] for item in industry_demand)
#     return render_template("mobile/demand/industry.html",
#                         subtitle = '(in Ha M)' if has_value > 0 else 'There are no industry in this block',
#                         industries = industry_demand, 
#                         chart_data = json.dumps(industry_demand),
#                         breadcrumbs= get_breadcrumbs(payload), 

iAndhra/app/templates/mobile/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DPR - {% block title %} {% endblock %}</title>
    <link rel="icon" type="image/png" href="{{url_for('static', filename='assets/drop.png')}}">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <!-- <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='scss/styles.css')}}"> -->
    <link id="theme-stylesheet" rel="stylesheet" type="text/css"  href="{{ theme_stylesheet }}">
    <style>

    
    /*End Bottom Menu*/
    </style>
</head>
<body>
    <!--Overlay-->
    <div id="loading-spinner" class="overlay">
        <!--Spinner-->
        <div id="loading-wrapper">
          <div id="loading-text">LOADING</div>
          <div id="loading-content"></div>
        </div>
    </div>
    <nav class="navbar fixed-top bg-primary justify-content-between">        
        <div class="ms-2">
            <a class="navbar-brand text-white" href="{{url_for('mobile.index')}}">
                <span class="me-2"><i class="fa-solid fa-droplet"></i></span>DPR</a>
        </div>
        <div>
            <button class="btn text-white" type="button" data-bs-toggle="offcanvas" 
            data-bs-target="#offcanvasMenu" aria-controls="offcanvasMenu">
            <i class="fa-solid fa-bars"></i>
            </button>
        </div>
      </nav>

    {% from 'mobile/components.html' import bottom_menu, toggle_button, progress_bar, 
    approve_button %}    
   <div class="container-fluid h-100">
    <div class="mt-5">&nbsp;</div>
   <!-- {#<div class="mt-6">
        {% if 'index' in request.path or 'home' in request.path or 'auth/' in request.path %}
        <div class="mt-5">&nbsp;</div> 
        {% else %}
        <label for="progress_bar" class="text-white fs-8 fw-bold">Validation Progress</label>
        {{progress_bar()}}
        {% endif %}
    </div>#} -->
    <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 mx-auto">   
    <div class="card border-primary text-center mt-3" id="dynamicCard">
        <div class="card-header bg-primary p-2 mb-0">
            {% if breadcrumbs %}
            <nav style="--bs-breadcrumb-divider: '|';" aria-label="breadcrumb">
                <ol class="breadcrumb fs-9 ms-3 mb-0 py-2">
                    <!-- <li class="breadcrumb-item "><a class=" link-underline link-underline-opacity-0" href="/home"><strong>Home</strong></a></li> -->
                {% for breadcrumb in breadcrumbs %}
                <li class="breadcrumb-item">
                    <a class="link-underline link-underline-opacity-0 
                    {% if loop.index == breadcrumbs | length %} text-white 
                    {% else %} link-light 
                    {% endif %}" href="{{breadcrumb.href}}">
                        {{breadcrumb.name}}
                    </a>
                </li> 
                {% endfor %}
                </ol>
            </nav> 
            {% endif %} 
        </div>
        <div class="card-body">            
            {% block content %}
            {% endblock %}            
        </div>
        <div class="card-footer bg-light fs-9 text-primary text-start">
            <div class="d-flex align-items-center">
            <span class="me-auto">{% if source %}Source: {{source}}{% endif %}</span>            
            {% if not is_approved %}
                {% if 'index' in request.path or 'home' in request.path or 'auth/' in request.path%}
                <div>&nbsp;</div>
                {% else %}
                {{approve_button()}}
                {% endif %}
            {% endif %}
            </div>
        </div>
    </div>     
</div>
   </div>
    <div class="fixed-bottom">
        {{toggle_button(labels=toggle_labels)}}        
        {{ bottom_menu(menu_array=menu|default([])) }}
    </div>
    <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasMenu" aria-labelledby="offcanvasMenu">
        <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasMenuLabel"><i class="fa-solid fa-droplet"></i>&nbsp;DPR</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <p><strong>Menu</strong></p>
            <div class="list-group list-group-flush fs-7">
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
                        Theme: {{ available_themes[current_theme].name }}
                    </button>
                    <ul class="dropdown-menu">
                        {% for theme_id, theme in available_themes.items() %}
                        <li>
                            <button class="dropdown-item theme-switcher" 
                                    data-theme="{{ theme_id }}"
                                    {% if theme_id == current_theme %}disabled{% endif %}>
                                {{ theme.name }}
                            </button>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                {% if current_user.is_authenticated %}
                    {% if current_user.isAdmin %}
                    <a class="list-group-item list-group-item-action py-3" href="{{url_for('auth.approve')}}"><i class="fa-solid fa-gauge"></i>&nbsp;Dashboard</a>
                    <a class="list-group-item list-group-item-action py-3" href="{{url_for('auth.reset_password')}}"><i class="fa-solid fa-unlock-keyhole"></i>&nbsp;Reset Password</a>
                    {% endif %}
                    <a class="list-group-item list-group-item-action py-3" href="{{url_for('auth.change_password')}}"><i class="fa-solid fa-user-pen"></i>&nbsp;Change Password</a>
                    <a href="{{url_for('mobile.home')}}" class="list-group-item list-group-item-action py-3"><i class="fa-solid fa-scale-unbalanced-flip"></i>&nbsp;Water Budget</a>
                    <a href="{{url_for('auth.logout')}}" class="list-group-item list-group-item-action py-3"><i class="fa-solid fa-lock"></i>&nbsp;Logout</a>
                {% else %}
                <a href="{{url_for('auth.login')}}" class="list-group-item list-group-item-action py-3"><i class="fa-solid fa-lock-open"></i>&nbsp;Login</a>
                <a href="{{url_for('mobile.index')}}" class="list-group-item list-group-item-action py-3"><i class="fa-solid fa-scale-unbalanced-flip"></i>&nbsp;Water Budget</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% for message in flash_message %}
    {% if message %}
    <div class="toast-container position-fixed bottom-0 end-0 p-3 mb-6">
        <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
          <div class="toast-header">
            <span class="me-2"><i class="fa-solid fa-droplet"></i></span>
            <strong class="me-auto">DPR says...</strong>
            <small></small>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
          <div class="toast-body" id="flashMesssageDiv">
            {{message}}
          </div>
        </div>
      </div> 
      {% endif %}   
      {% endfor %}
    <!--SCRIPTs -->
    <script src="https://cdn.jsdelivr.net/npm/echarts@5.5.1/dist/echarts.min.js"></script>
    <script src="{{url_for('static', filename='js/popper.min.js')}}"></script> 
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/main.js')}}"></script> 
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const themeSwitchers = document.querySelectorAll('.theme-switcher');
            
            themeSwitchers.forEach(button => {
                button.addEventListener('click', function() {
                    const theme = this.dataset.theme;
                    
                    // Disable all buttons temporarily
                    themeSwitchers.forEach(btn => btn.disabled = true);
                    
                    fetch('/iandhra/change-theme', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                        },
                        body: JSON.stringify({ theme: theme })
                    })
                    .then(response => response.json())
                    .then(data => {
                        if (data.success) {
                            // Update stylesheet
                            const styleSheet = document.getElementById('theme-stylesheet');
                            styleSheet.setAttribute('href', data.stylesheet);
                            
                            // Update button states
                            themeSwitchers.forEach(btn => {
                                btn.disabled = btn.dataset.theme === theme;
                            });
                            
                            // Reload Bootstrap components if needed
                            // Add any additional theme-switch logic here
                        }
                    })
                    .catch(error => {
                        console.error('Error:', error);
                        // Re-enable all buttons on error
                        themeSwitchers.forEach(btn => btn.disabled = false);
                    });
                });
            });
        });
    </script>    
    <!-- <script>
        // Tooltip
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
        
        // Toggle dropdown
        const dropdownElementList = document.querySelectorAll('.dropdown-toggle')
        const dropdownList = [...dropdownElementList].map(dropdownToggleEl => new bootstrap.Dropdown(dropdownToggleEl))

        // toggle toast
        const toastDiv = document.getElementById('liveToast');
        const flash_message = document.getElementById('flashMesssageDiv')
        if (flash_message) {
                if (flash_message.innerText.trim() !== 'false' && flash_message.innerText.trim() !== '') {
                const toastBootstrap = bootstrap.Toast.getOrCreateInstance(toastDiv);
                toastBootstrap.show();
            }
        }
        document.addEventListener('DOMContentLoaded', () => {
            const bottomMenu = document.querySelector('.fixed-bottom.bg-dark.bottom-menu.fade-in');
            if (bottomMenu){bottomMenu.classList.add('show')}            
        });
        function toggleSpinner() {
            const spinner = document.getElementById('loading-spinner');
            spinner.style.display = (spinner.style.display === 'none' || spinner.style.display === '') ? 'block' : 'none';
            }
        const carousel = document.querySelector("#cardCarousel");
        const radio1 = document.querySelector("#radio-1");
        const radio2 = document.querySelector("#radio-2");
        if (carousel){
            document.querySelectorAll('.tab').forEach((label, index) => {
            label.addEventListener('click', () => {
                // Update the carousel slide using Bootstrap's API
                const carousel = new bootstrap.Carousel('#cardCarousel');
                carousel.to(index);
                });
            });
            // Add event listener for the carousel slide
            if (radio1){
                    carousel.addEventListener("slid.bs.carousel", function (event) {
                    const activeIndex = [...carousel.querySelectorAll(".carousel-item")].indexOf(
                        carousel.querySelector(".carousel-item.active")
                    );

                    if (activeIndex === 0) {
                        radio1.checked = true;
                    } else if (activeIndex === 1) {
                        radio2.checked = true;
                    }
                });
            }            
        }
        
        function adjustCardHeight() {
        const card = document.getElementById('dynamicCard');
        const screenHeight = window.innerHeight;
        const cardHeight = screenHeight * 0.60; // 60% of screen height
        card.style.height = `${cardHeight}px`;
    }

    // Adjust the card height on page load
    // adjustCardHeight();

    // Adjust the card height on window resize
    window.addEventListener('resize', adjustCardHeight);
    </script> -->
    {% block scripts %}
    {% endblock %}
    <!--END SCRIPTS-->
</body>
</html>

iAndhra/app/templates/mobile/home.html
{% extends 'mobile/base.html' %}
{% block title %} Water Budget {% endblock %}
{% from 'mobile/components.html' import chart, table_title, table_head %}
{% block content %}
<div id="cardCarousel" class="carousel slide">
    <div class="carousel-inner">
      <div class="carousel-item active">        
        {{chart()}}
      </div>
      <div class="carousel-item">
        {{table_title(title='Block Level Water Budget', subtitle='(All values are in Ha M)')}}
        <!-- <div id="#radio-button" class="d-flex justify-content-around fs-7 fw-bold py-1">
            <span>Human Consumption: </span>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="55" checked>
                <label class="form-check-label" for="inlineRadio1">55 L</label>
              </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="70">
                <label class="form-check-label" for="inlineRadio2">70 L</label>
              </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio3" value="130">
                <label class="form-check-label" for="inlineRadio3">130 L</label>
              </div>
        </div> -->
        <table class="table table-bordered border-light table-sm fs-8 mb-0">
            {{table_head(headings=[
                {'heading':'Description','subheading':''},
                {'heading':'Value','subheading':''}])}}
          <!-- <thead class="text-center">
              <tr class="bg-light">
                  <th>Description</th>
                  <th>Value</th>
              </tr>
          </thead> -->
          <tbody>
              <tr>
                  <td colspan="2" class="fw-bold bg-opacity-50 p-0" style="background-color: #EB78C7">Demand</td>
              </tr>
              {% for row in demand_side %}
              <tr>
                  <td class="text-start py-0">{{row.category | title}}</td>
                  <td class="text-end py-0">{{row.water_value|indian_format}}</td>
              </tr>
              {% endfor %}
              <tr>
                  <td colspan="2" class="fw-bold bg-opacity-50 p-0" style="background-color:#B492FF">Supply</td>
              </tr>
              {% for row in supply_side %}
              <tr>
                  <td class="text-start py-0">{{row.category | title}}</td>
                  <td class="text-end py-0">{{row.water_value|indian_format}}</td>
              </tr>
              {% endfor %}
              <tr>
                  <td colspan="2" class="fw-bold bg-opacity-50 text-center p-0" style="background-color: #E592FA">Water Budget</td>
              </tr>
              {% for row in water_budget %}
              <tr>
                  <td class="text-start py-0">{{row.category | title}}</td>
                  <td class="text-end py-0">{{row.water_value|indian_format}}</td>
              </tr>
              {% endfor %}
              <tr>
                {% set total_supply = water_budget[1]['water_value'] %}
                {% set total_demand = water_budget[0]['water_value'] %}
                {% set water_budget = total_supply - total_demand %}
                <td class="text-start py-0 text-{% if water_budget < 0 %}danger{% else %}success{% endif %}-emphasis">{% if water_budget < 0 %}Deficient{% else %}Surplus{% endif %}</td>
                <td class="text-end py-0 text-{% if water_budget < 0 %}danger{% else %}success{% endif %}-emphasis">{{water_budget|indian_format}}</td>
              </tr>
          </tbody>
      </table>
      {% if current_user.is_authenticated %}
      <div class="d-none d-md-block"><a href="{{url_for('mobile.print')}}" target="_blank" class="btn btn-outline-dark mx-auto btn-sm mt-3">Print</a></div>  
      {% endif %}    
      </div>
    </div>
  </div>
  <input type="hidden" name="chartData" id="chartData" value="{{chart_data}}"> 
{% endblock %}
{% block scripts %}
<script>
// echart
var chartDom = document.getElementById('main');
    var myChart = echarts.init(chartDom);
    let chart_data = JSON.parse(document.getElementById('chartData').value);
    const chart_titles = ['Total Water Demand','Total Water Supply', 'Water Budget']
    var option;
    const data = chart_data;        
    option = {
        title:{
            text: chart_titles[0],
            left: 'center',
        },
        xAxis: {
            type: 'category',
            data: getCategories(data[0]),
            axisLabel: {
                show: true,
                rotate: 45,
                textStyle: {
                fontSize: 8
                }
            }
        },
        yAxis: {
            type: 'value'
        },
        series: [
            {
            label: {
                show: true,
                position: 'inside',
                formatter: function (params){
                if (params.value > 0 ) {
                    return params.value + '%'
                } 
                else {return ''} 
                
                },
                textStyle:{
                fontSize: 8,
                }
            },
            data: transformArray(data[0]),
            type: 'bar'
            }
        ]
        };

        idx = 0
        setInterval(() => {
        myChart.setOption({
            title:{
                text: chart_titles[idx],
                left: 'center',
            },
            xAxis: {
            type: 'category',
            data: getCategories(data[idx]),
            axisLabel: {
                show: true,
                rotate: 45,
                textStyle: {
                fontSize: 8
                }
            }
            },
            yAxis: {
            type: 'value',
            min: 0,
            max: 100,
            },
            series: [
            {
                
                label: {
                show: true,
                position: 'inside',
                formatter:function (params){
                if (params.value > 0 ) {
                    return params.value + '%'
                } 
                else {return ''} 
                
                },
                textStyle:{
                fontSize: 8,
                }
                },
                data: transformArray(data[idx]),
                type: 'bar'
            }
            ]
        });
        idx=idx+1;
        if (idx==3) { idx=0 }
        }, 5000);



        function transformArray(input_array) {
            let output_array = [];
            input_array.forEach((value, idx) => {
                object = {
                value: value['value'],
                itemStyle: {
                    color: value['background']
                }
                }
                output_array.push(object);
            });
            return output_array;
            }

        function getCategories(input_array) {
            const output_array = input_array.map(item => item.category);
        // output_array=[];
        // input_array.forEach((element, idx)=>{
        //     output_array.push(element['category'])
        // });
        return output_array;
        }

    option && myChart.setOption(option);

</script>
{% endblock %}